name: jsonplaceholder_with_bloc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  json_serializable: ^6.1.4
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
